baseurl = "/"
languageCode = "en-us"
title = "MaaS API"
theme = "hugo-creative-theme"
googleAnalytics = ""

[[menu.main]]
  name = "Documentation"
  weight = -110
  url = "https://maasglobal.github.io/maas-tsp-api/"

[[menu.main]]
  name = "Sourcecode"
  weight = -110
  url = "https://github.com/maasglobal/maas-tsp-api"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more information take a look at the README.

  # To provide some metadata for search engines feel free to add some
  # information about you and your website.
  name = "MaaS Global Oy"
  # description = "Your description"

  # The path must be relative to the static folder
  favicon = "favicon.ico"


# Navigation
[params.navigation]
	brand = "MaaS API"

[params.navigation.links]
	about     = "About"
	services  = "Services"
	portfolio = "Portfolio"
	contact   = "Contact"

# Hero section
[params.hero]
  # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
  slogan     = "Mobility as a Service API"
  subtitle   = "Connecting the world of mobility providers."
  buttonText = "Find out more"


# About section
[params.about]
	headline    = "Unified mobility ecosystem"
	description = "A common standard for mobility data flow."
	buttonText  = "Get started"
	link = "https://maasglobal.github.io/maas-tsp-api/"

# Service section
[params.services]
  headline = "Aspects"

[[params.services.list]]
  icon = "fa-map-signs"
  title = "Routes"
  description = "Connect the dots to get people to their destinations."

[[params.services.list]]
  icon = "fa-clock-o"
  title = "Schedules"
  description = "Keep track of timetables to plan the optimal journey."

[[params.services.list]]
	icon = "fa-diamond"
	title = "Product offerings"
	description = "Let downstream service providers discover your products."

[[params.services.list]]
	icon = "fa-paper-plane"
	title = "Bookings and reservations"
	description = "Customers can book tickets directly with your service."

[[params.services.list]]
  icon = "fa-check-square-o"
  title = "Validation"
  description = "Transportation companies ensure that bookings are valid."

[[params.services.list]]
  icon = "fa-newspaper-o"
  title = "Service announcements"
  description = "Publish information about new and upcoming services."

[[params.services.list]]
  icon = "fa-heart"
  title = "Feedback"
  description = "Learn from customers to improve your service."

[[params.services.list]]
  icon = "fa-credit-card"
  title = "Payments"
  description = "Make sure all parties get a fair share and good value."


# Portfolio modals
[params.portfolio.modal]
  client = "Client"
  date = "Date"
  category = "Category"
  buttonText = "Close"

    # Aside section
[params.aside]
  headline = "Shape the future of MaaS APIs"

[params.aside.button]
	text = "Contribute"
	link = "https://github.com/maasglobal/maas-tsp-api"

	# Contact section
	# [params.contact]
	# 	headline = "Let's Get In Touch!"
	# 	description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
	# 	phone = "123-456-6789"
	# 	email = "feedback@startbootstrap.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
