baseurl = "/"
languageCode = "en-us"
title = "MaaS API"
theme = "hugo-creative-theme"
googleAnalytics = ""

[[menu.main]]
  name = "API Documentation"
  weight = -110
  url = "https://maasglobal.github.io/maas-tsp-api/"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more information take a look at the README.

  # To provide some metadata for search engines feel free to add some
  # information about you and your website.
  name = "MaaS Global Oy"
  # description = "Your description"

  # The path must be relative to the static folder
  favicon = "favicon.ico"


# Navigation
[params.navigation]
	brand = "MaaS API"

[params.navigation.links]
	about     = "About"
	aspects  = "Aspects"
	portfolio = "Portfolio"
	contact   = "Contact"
  contribute = "Sourcecode"

# Hero section
[params.hero]
  # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
  slogan     = "Mobility as a Service API"
  subtitle   = "Connecting the world of mobility providers"
  buttonText = "Find out more"


# About section
[params.about]
	headline    = "Unified mobility ecosystem"
	description = "A common standard for mobility data flow"
	buttonText  = "View API Documentation"
	link = "https://maasglobal.github.io/maas-tsp-api/"

# Service section
[params.aspects]
  headline = "Aspects"

[[params.aspects.list]]
  icon = "fa-map-signs"
  title = "Routes"
  description = "Connect the dots to get people to their destinations."

[[params.aspects.list]]
  icon = "fa-clock-o"
  title = "Schedules"
  description = "Keep track of timetables to plan the optimal journey."

[[params.aspects.list]]
	icon = "fa-diamond"
	title = "Products"
	description = "Let service providers discover your products."

[[params.aspects.list]]
	icon = "fa-paper-plane"
	title = "Bookings"
	description = "Customers can book tickets directly with your service."

[[params.aspects.list]]
  icon = "fa-check-square-o"
  title = "Validation"
  description = "Transportation providers check that bookings are valid."

[[params.aspects.list]]
  icon = "fa-newspaper-o"
  title = "Announcements"
  description = "Announce new and upcoming services, outages, etc."

[[params.aspects.list]]
  icon = "fa-heart"
  title = "Feedback"
  description = "Learn from customers to improve your service."

[[params.aspects.list]]
  icon = "fa-credit-card"
  title = "Payments"
  description = "Ensure all parties get a fair share and good value."


# Portfolio modals
[params.portfolio.modal]
  client = "Client"
  date = "Date"
  category = "Category"
  buttonText = "Close"

# Aside section
[params.contribute]
  headline = "Shape the future of MaaS APIs"

[params.contribute.button]
	text = "Sourcecode"
	link = "https://github.com/maasglobal/maas-tsp-api"

#Contact section
[params.contact]
	headline = "Get in touch"
	# description = "Help us build the fuuuuuuuuture!"
	# phone = "123-456-6789"
	email = "tech@maas.global"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
